### ISSUE TITLE
Документация

### ISSUE THREAD

**Issue by tsukanov-as** [ComdivByZero/vostok#1]
Только начал знакомиться. Через tdm-gcc собрал с пол пинка.
Но дальше возникают вопросы...
Мне кажется нужна краткая техническая дока :)
1. Описание языков (если Обероны оригинальные, то можно наверно ссылки на реализованные репорты приложить)
2. Управление памятью (mark & sweep по дефолту? как выбрать подсчет ссылок?)
3. Какой состав планируется у стандартной библиотеки?
4. Прочие детали реализации.

ps Если все можно понять по исходникам, то все равно нужен как минимум краткий обзор как ориентироваться в исходниках

**Comment by ComdivByZero** [comment]
Соглашусь, что нужна документация, но пока не дошёл до этого. Отвечу пока здесь.
1. Оберон оригинальный, насколько это можно сказать о неполном описании языка. Сейчас не хватает CASE по RECORD.
2. Сейчас по умолчанию без освобождения. Для того, чтобы полноценно использовать подсчёт ссылок, его нужно доделать. Сейчас он, скорее, в виде доказательства концепции.
3. Библиотека не продумывалась. Хотел использовать дубовые требования, но они оказались довольно неудачными, но где возможно, следую им.

**Comment by tsukanov-as** [comment]
> Сейчас по умолчанию без освобождения
Ручное управление? А как руками освобождать?

**Comment by ComdivByZero** [comment]
Не ручное управление, а без освобождения, что хорошо подходит для короткоживущих утилит командной строки. Если есть интерес к освобождению подсчётом ссылок, могу активизировать эту тему. Ручное удаление вообще не планируется, потому что его безопасный вариант имеет накладные расходы, схожие с подсчётом, но при этом менее удобен.

**Comment by tsukanov-as** [comment]
Ну лично мне интересен только подсчет ссылок, да. Причем устроит самый тупой вариант без отслеживания циклов.

**Comment by ComdivByZero** [comment]
Самый тупой - это без цепочек, то есть, для освобождения списка, нужно по нему пройтись, зануляя указатели явно. Сейчас такой, но давно не проверялся.

**Comment by ComdivByZero** [comment]
Минимальное количество технической документации было добавлено.
